Repository Nichi-In-Dev-Dept-1/telenet_hinanjo_web_fe_nextjs, pull requests merged in 2023-10, with the labels that each got.

#22 Fix: UI/UX / Corrections
  public/locales/en/lang.json
  public/locales/jp/lang.json
  public/themes/lara-light-indigo/theme.css
  src/components/datatable/normalTable.js
  src/components/modal/deleteModal.js
  src/layout/context/layoutcontext.js
  src/pages/_app.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/login/index.js
  src/services/dashboard.services.js
  src/services/index.js
  src/styles/components/_inputSwitch.scss
  src/styles/pages/_dashboard.scss
  src/utils/constant.js
Labels: corrections

#27 Likith UI/UX
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/datatable/normalTable.js
  src/helper/index.js
  src/pages/admin/dashboard/index.js
  src/utils/constant.js
Labels: integration

#28 Update: Integration / #2116 && #2117
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/datatable/normalTable.js
  src/components/modal/deleteModal.js
  src/layout/context/layoutcontext.js
  src/pages/admin/dashboard/index.js
  src/services/dashboard.services.js
Labels: integration

#29 Fix: Dashboard changes
  src/components/datatable/normalTable.js
  src/layout/context/layoutcontext.js
  src/pages/admin/dashboard/index.js
Labels: integration

#30 Fix: UI/UX / #2208 && #2207
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/_app.js
  src/pages/admin/forgot-password/index.js
  src/pages/admin/reset-password/index.js
Labels: corrections

#31 #2099
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/datatable/normalTable.js
  src/components/datatable/rowExpansionTable.js
  src/components/dropdown/dropdownSelect.js
  src/components/modal/deleteModal.js
  src/helper/adminEvacueeFamilyDetailService.js
  src/layout/AppTopbar.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/qrcode/csv/import/index.js
  src/pages/admin/staff-management/index.js
  src/pages/admin/stockpile/summary/index.js
  src/styles/components/_dialog.scss
  src/styles/components/_table.scss
  src/styles/pages/_dashboard.scss
  src/styles/variables.scss
Labels: bug

#32 created Statistics screen
  src/pages/admin/statistics/index.js
  src/utils/constant.js
Labels: design

#33 #2221
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/StaffManagementEditModal.js
  src/components/modal/adminManagementCreateModal.js
  src/components/modal/adminManagementDetailModal.js
  src/components/modal/adminManagementEditModal.js
  src/components/modal/deleteModal.js
  src/components/modal/staffManagementDetailModal.js
  src/pages/admin/admin-management/create/index.js
  src/pages/admin/admin-management/detail/[id].js
  src/pages/admin/admin-management/edit/[id].js
  src/pages/admin/dashboard/index.js
  src/pages/admin/place/detail/[id].js
  src/pages/admin/qrcode/csv/import/index.js
  src/pages/admin/staff-management/create/index.js
  src/pages/admin/staff-management/detail/[id].js
  src/pages/admin/staff-management/edit/[id].js
  src/pages/admin/stockpile/master/create/index.js
  src/pages/admin/stockpile/master/edit/[id].js
  src/pages/admin/stockpile/master/index.js
  src/styles/components/_btn.scss
  src/styles/pages/_dashboard.scss
  src/styles/pages/pages.scss
  src/styles/variables.scss
Labels: bug

#34 Likith UI/UX
  src/layout/AppMenu.js
  src/layout/AppMenuitem.js
  src/layout/context/layoutcontext.js
  src/layout/layout.js
  src/pages/_app.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/external/family/index.js
  src/pages/admin/history/place/index.js
  src/pages/admin/material/index.js
  src/pages/admin/place/index.js
  src/pages/admin/qrcode/csv/import/index.js
  src/pages/admin/questionnaire/index.js
  src/pages/admin/setting/index.js
  src/pages/admin/shortage-supplies/index.js
  src/pages/admin/special/care/index.js
  src/pages/admin/staff-management/index.js
  src/pages/admin/statistics/index.js
  src/pages/admin/stockpile/master/index.js
  src/pages/admin/stockpile/summary/index.js
  src/styles/layout/layout.scss
  src/styles/layout/loader.scss
Labels: design, corrections

#36 Likith UI/UX
  package.json
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/_app.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/forgot-password/index.js
  src/pages/admin/login/index.js
  src/pages/admin/place/index.js
  src/pages/admin/reset-password/index.js
  src/services/authn_authz.services.js
  src/utils/api.js
Labels: bug, corrections

#38 Integration: Dashboard & Other fixes
  public/locales/en/lang.json
  src/components/datatable/normalTable.js
  src/pages/admin/dashboard/index.js
  src/styles/layout/_main.scss
Labels: integration

#39 Integration: Dashboard & Other fixes
  src/components/datatable/normalTable.js
Labels: corrections

#41 Integration: Dashboard
  src/services/dashboard.services.js
Labels: integration

#42 Fix: UI/UX / Reset
  public/locales/jp/lang.json
Labels: corrections

#43 Fix&Check: UI/UX / Reset routing issues
  src/pages/_app.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/qrcode/csv/import/index.js
Labels: design, corrections

#44 Fix&Check: UI/UX / Reset routing issues
  src/pages/_app.js
Labels: corrections

#45 Check: Issues
  src/pages/_app.js
Labels: corrections

#46 Check: Issues
  src/pages/_app.js
Labels: bug, corrections

#47 #2226
  src/components/datatable/normalTable.js
  src/components/datatable/rowExpansionTable.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/staff-management/index.js
  src/styles/pages/_common.scss
  src/styles/variables.scss
  src/utils/constant.js
Labels: bug

#48 #2229
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/StaffManagementEditModal.js
  src/components/modal/adminManagementCreateModal.js
  src/components/modal/adminManagementDetailModal.js
  src/components/modal/adminManagementEditModal.js
  src/components/modal/adminManagementImportModal.js
  src/components/modal/staffManagementDetailModal.js
  src/components/upload/inputFile.js
  src/layout/AppTopbar.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/staff-management/index.js
  src/styles/components/_inputFile.scss
  src/styles/components/components.scss
  src/styles/layout/_topbar.scss
  src/styles/pages/_common.scss
  src/styles/variables.scss
  src/utils/constant.js
Labels: bug

#49 Integration: Shortage supplies
  src/helper/index.js
  src/pages/admin/shortage-supplies/index.js
  src/services/index.js
  src/services/shortage_supplies.service.js
Labels: integration

#53 Likith UI/UX
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/datatable/normalTable.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/shortage-supplies/index.js
  src/services/shortage_supplies.service.js
  src/styles/pages/_shortageSupplies.scss
  src/styles/pages/pages.scss
Labels: design, integration

#54 #2237 #2229
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/input/inputLeftRightGroup.js
  src/components/link/linker.js
  src/components/modal/StaffManagementEditModal.js
  src/components/modal/adminManagementDeleteModal.js
  src/components/modal/stockPileSummaryMailSettingsModal.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/staff-management/index.js
  src/pages/admin/stockpile/summary/index.js
  src/styles/components/_input.scss
  src/styles/pages/_place.scss
  src/styles/pages/_stockpileSummary.scss
Labels: bug

#55 FIx: Merge conflicts
  src/pages/admin/material/index.js
  src/pages/admin/stockpile/master/index.js
Labels: corrections

#57 Update&Fix: Integration / UI/UX ( #1997 )
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/detailModal.js
  src/pages/admin/shortage-supplies/index.js
Labels: design, corrections, integration

#58 Fix: Integration ( #1997 )
  src/pages/admin/shortage-supplies/index.js
Labels: corrections, integration

#59 Fix: UI/UX / Shortage supplies
  src/pages/admin/shortage-supplies/index.js
Labels: design, corrections

#60 Likith UI/UX
  public/locales/en/lang.json
  public/locales/jp/lang.json
  public/themes/lara-light-indigo/theme.css
  src/pages/admin/qrcode/csv/import/index.js
  src/pages/admin/shortage-supplies/index.js
  src/services/index.js
  src/services/qr_code_create.services.js
  src/services/shortage_supplies.service.js
Labels: design, integration

#61 #2022 #2171
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/datatable/rowExpansionTable.js
  src/components/input/index.js
  src/components/input/inputLeftRightGroupFloat.js
  src/components/modal/changePasswordModal.js
  src/components/modal/emailSettings.js
  src/components/modal/index.js
  src/layout/AppTopbar.js
  src/pages/admin/staff-management/index.js
  src/services/authn_authz.services.js
Labels: design

#63 Likith UI/UX
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/detailModal.js
Labels: design, corrections

#64 Likith UI/UX
  .eslintrc.json
  src/components/modal/detailModal.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/shortage-supplies/index.js
  src/services/material.service.js
  src/services/place.service.js
  src/services/qr_code_create.services.js
  src/styles/components/_dialog.scss
Labels: corrections

#68 Fix: Build issues
  src/pages/admin/evacuation/family-detail/index.js
  src/utils/api.js
Labels: corrections

#69 #2246
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/changePasswordModal.js
  src/layout/AppFooter.js
  src/styles/layout/_topbar.scss
Labels: bug

#70 Update: Integration / QR code create
  src/pages/admin/qrcode/csv/import/index.js
  src/services/common.services.js
  src/services/index.js
  src/services/qr_code_create.services.js
Labels: corrections, integration

#74 Fix: UI/UX / Integration ( QR code create )
  src/helper/index.js
  src/pages/admin/qrcode/csv/import/index.js
  src/services/index.js
  src/services/statistics.services.js
Labels: design, corrections, integration

#76 Special Care Screen Design
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/SpecialCareEditModal.js
  src/components/modal/commonDialog.js
  src/components/modal/index.js
  src/helper/adminSpecialCareService.js
  src/pages/admin/special/care/create/index.js
  src/pages/admin/special/care/edit/[id].js
  src/pages/admin/special/care/index.js
Labels: design

#80 Fix: Build issues
  .eslintrc.json
  src/components/modal/stockpileCreateEditModal.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/material/index.js
  src/pages/admin/stockpile/master/index.js
Labels: corrections

#81 Fix: API / Infinite loop issues
  src/utils/api.js
Labels: bug, corrections

#84 #2267
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/SpecialCareEditModal.js
  src/layout/AppTopbar.js
  src/pages/admin/special/care/index.js
Labels: bug

#88 Fix: Build issues
  src/helper/index.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/statistics/index.js
  src/services/qr_code_create.services.js
  src/services/statistics.services.js
  src/utils/constant.js
Labels: bug, corrections

#91 Update: #2011 / Statistics
  src/pages/admin/statistics/index.js
Labels: corrections, integration

#92 Likith UI/UX
  src/pages/admin/statistics/index.js
Labels: corrections

#95 Fix: UI/UX & Other issues
  src/components/modal/detailModal.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/shortage-supplies/index.js
  src/pages/admin/statistics/index.js
Labels: design, corrections

#99 Fix: Statistics / Build issues
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/admin/external/family/list/index.js
  src/pages/admin/statistics/index.js
  src/styles/pages/_common.scss
Labels: bug, design, corrections

#102 Fix: Pagination / Shortage supplies
  src/pages/admin/dashboard/index.js
  src/pages/admin/shortage-supplies/index.js
  src/services/shortage_supplies.service.js
Labels: bug, design, corrections

#104 Fix: Statistics / #2275
  src/pages/admin/statistics/index.js
Labels: corrections

#106 Fix: Build issues
  src/pages/admin/external/family/detail/index.js
Labels: corrections

#107 Update:UI/UX /Settings screen design and import modal bug fix
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/checkbox/normalCheckbox.js
  src/components/input/inputNumberFloatLabel.js
  src/components/modal/adminManagementImportModal.js
  src/pages/admin/setting/index.js
  src/pages/admin/special/care/index.js
  src/styles/components/_checkbox.scss
  src/styles/components/_dialog.scss
  src/styles/components/_dragDrop.scss
  src/styles/components/components.scss
  src/styles/pages/_historyPlace.scss
Labels: design

#108 Fix: Build issues
  src/pages/admin/setting/index.js
Labels: corrections

#114 Fix: Statisitics / Corrections
  src/pages/admin/statistics/index.js
Labels: corrections

#116 Fix:UI/UX /Settings screen design
  public/locales/en/lang.json
  src/components/dragNdrop/questionnairesView.js
  src/components/radioButton/radioBtn.js
  src/components/switch/inputSwitch.js
  src/pages/admin/setting/index.js
  src/styles/components/_radioBtn.scss
  src/styles/components/components.scss
Labels: bug

#120 Fix: QR code create / Issues
  src/pages/admin/qrcode/csv/import/index.js
  src/pages/admin/statistics/index.js
  src/services/qr_code_create.services.js
Labels: bug

#121 special care integration
  src/pages/admin/special/care/index.js
  src/services/special_care.service.js
Labels: integration

#124 Fix: Build & Statistics issues
  src/pages/admin/external/family/index.js
  src/pages/admin/statistics/index.js
Labels: corrections

#128 Fix: Build issues
  src/components/modal/staffManagementDetailModal.js
  src/pages/admin/staff-management/index.js
Labels: corrections

#129 setting syste screen integration
  src/components/dragNdrop/dnd.js
  src/pages/admin/place/detail/index.js
  src/pages/admin/place/edit/index.js
  src/pages/admin/place/index.js
  src/pages/admin/setting/index.js
  src/redux/place/index.js
  src/redux/rootReducer.js
  src/services/index.js
  src/services/system_setting.services.js
  src/utils/constant.js
Labels: integration

#131 Update: Admin management / UI/UX & Integration
  public/locales/en/lang.json
  src/components/modal/adminManagementCreateModal.js
  src/components/modal/adminManagementDeleteModal.js
  src/components/modal/adminManagementEditModal.js
  src/pages/admin/admin-management/index.js
  src/services/admin_management.services.js
Labels: design, integration

#132 #2019 #2020
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/input/input.js
  src/components/questionarrie/index.js
  src/components/questionarrie/template/baseTemplate.js
  src/helper/adminQuestionarieService.js
  src/pages/admin/questionnaire/index.js
  src/pages/admin/questionnaire/individual.js
  src/pages/admin/questionnaire/master.js
  src/pages/admin/setting/index.js
  src/styles/components/_dragDrop.scss
Labels: design

#136 #2296
  public/themes/lara-light-indigo/theme.css
Labels: bug

#137 Fix:UI/UX / Date picker issue fix
  src/components/date&time/dateTimeCalendarFloatLabel.js
Labels: bug

#140 Fix: Breakage issue
  src/layout/AppMenu.js
Labels: corrections

#141 Update: Login / Toast
  src/services/authn_authz.services.js
Labels: corrections

#143 Fix: Map / Assets
  public/layout/images/logo_admin.png
  public/layout/images/map/map_active.png
  public/layout/images/map/map_active_blue.png
  public/layout/images/map/map_active_full.png
  public/layout/images/map/map_active_red.png
  public/layout/images/map/map_inactive.png
  public/layout/images/map/map_inactive_gray.png
  public/layout/images/map/my_location.png
Labels: design

#144 Fix: Build issues
  src/components/date&time/dateCalendarFloatLabel.js
  src/components/date&time/timeCalendarFloatLabel.js
Labels: corrections

#148 Fix: Build issues
  src/pages/admin/dashboard/index.js
Labels: corrections

#151 Likith UI/UX
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/dropdown/dropdownSelect.js
  src/helper/publicEvacueeService.js
  src/helper/publicEvacueesService.js
  src/layout/AppTopbar.js
  src/layout/context/layoutcontext.js
  src/layout/layout.js
  src/pages/admin/dashboard/index.js
  src/pages/user/dashboard/index.js
  src/pages/user/list/index.js
  src/pages/user/public-evacuees/index.js
  src/pages/user/register/member/index.js
  src/redux/layout/index.js
  src/redux/redux-persist-config.js
  src/redux/rootReducer.js
  src/services/index.js
  src/services/public_evacuees.services.js
  src/styles/pages/_userDashboard.scss
  src/styles/pages/pages.scss
  src/styles/variables.scss
Labels: design, corrections, integration

#152 Updated minor date bug fixed
  src/helper/index.js
  src/pages/admin/evacuation/family-detail/index.js
Labels: bug

#153 Likith UI/UX
  src/pages/_app.js
  src/pages/staff/login/index.js
  src/pages/user/dashboard/index.js
  src/services/authn_authz.services.js
Labels: corrections, integration

#154 Fix:UI/UX /Admin management
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/adminManagementCreateModal.js
  src/components/modal/adminManagementEditModal.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/staff-management/index.js
  src/services/admin_management.services.js
Labels: bug

#155 Fix:UI/UX / Special care
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/SpecialCareEditModal.js
  src/pages/admin/special/care/index.js
Labels: bug

#156 Updated minor design bug fixed
  public/locales/jp/lang.json
  src/pages/admin/history/place/index.js
  src/styles/pages/_historyPlace.scss
Labels: corrections

#157 Update: UI/UX / Integration ( Staff / Login, Forgot & Reset )
  src/layout/AppTopbar.js
  src/pages/admin/forgot-password/index.js
  src/pages/staff/forgot-password/index.js
  src/pages/staff/index.js
  src/pages/staff/reset-password/index.js
  src/services/authn_authz.services.js
Labels: design, corrections, integration

#158 Update: Integration / User ( List )
  src/pages/_app.js
  src/pages/user/list/index.js
  src/services/index.js
  src/services/user_place_list.services.js
Labels: corrections, integration

#159 Stockpile History design and Staff management issue fix
  .vscode/settings.json
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/StaffManagementEditModal.js
  src/helper/staffStockpileHistoryService.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/staff-management/index.js
  src/pages/staff/stockpile/history/index.js
  src/utils/constant.js
Labels: bug, design

#160 Fix:UI/UX / Table width fix for large content
  src/pages/admin/dashboard/index.js
  src/pages/admin/history/place/index.js
  src/pages/admin/place/index.js
  src/pages/admin/shortage-supplies/index.js
  src/pages/user/list/index.js
Labels: bug

#161 Update:UI/UX / Stockpile list
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/helper/staffStockpileDashboardService.js
  src/pages/staff/stockpile/dashboard/index.js
  src/pages/staff/stockpile/history/index.js
Labels: design

#163 Harish dev
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/chart/index.js
  src/components/incrementDecrement/counter.js
  src/components/map/GoogleMapComponent.js
  src/helper/index.js
  src/layout/AppFooter.js
  src/layout/AppTopbar.js
  src/pages/staff/dashboard/index.js
  src/pages/staff/supplies/index.js
  src/services/index.js
  src/services/staff_dashboard.service.js
  src/services/supplies.services.js
  src/styles/components/_input.scss
  src/styles/pages/_staffDashBoard.scss
  src/styles/pages/pages.scss
Labels: design, integration

#164 Harish dev
  src/components/chart/index.js
  src/pages/staff/dashboard/index.js
  src/utils/constant.js
Labels: integration

#166 Fix: Build issuess
  src/pages/staff/external/family-list/index.js
Labels: corrections

#167 lang fixes
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/admin/place/create/index.js
  src/pages/admin/place/edit/index.js
Labels: bug

#168 Staff stockpile Add, Import, View Image screen design
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/index.js
  src/components/modal/staffStockpileCreateModal.js
  src/pages/admin/material/index.js
  src/pages/admin/stockpile/master/index.js
  src/pages/staff/stockpile/dashboard/index.js
Labels: bug, design

#169 Update:UI/UX / Stockpile Edit Screen
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/date&time/dateCalendarFloatLabel.js
  src/components/modal/index.js
  src/components/modal/staffStockpileCreateModal.js
  src/components/modal/staffStockpileEditModal.js
  src/pages/staff/stockpile/dashboard/index.js
  src/styles/components/_dropdown.scss
Labels: design

#170 Update: UI/UX / Integration / #2032
  src/layout/AppMenu.js
  src/pages/admin/history/place/index.js
  src/pages/staff/dashboard/index.js
  src/pages/staff/stockpile/history/index.js
  src/services/index.js
  src/services/stockpile_history.services.js
Labels: design, corrections, integration

#171 Harish dev
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/dropdown/selectFloatLabel.js
  src/components/input/textAreaFloatLabel.js
  src/components/modal/adminManagementImportModal.js
  src/pages/admin/place/edit/index.js
  src/pages/admin/setting/index.js
  src/pages/staff/supplies/index.js
  src/services/supplies.services.js
  src/utils/constant.js
Labels: design, corrections, integration

#172 Fix:UI/UX / Import component issue
  src/components/modal/adminManagementImportModal.js
Labels: bug

#176 Fix:UI/UX / Dropdown width
  public/themes/lara-light-indigo/theme.css
  src/components/modal/emailSettings.js
  src/components/modal/stockPileSummaryMailSettingsModal.js
  src/pages/admin/components_demo/index.js
  src/styles/pages/_historyPlace.scss
Labels: bug

#177 Fix: Build issues
  src/components/modal/stockPileSummaryMailSettingsModal.js
  src/pages/_app.js
  src/pages/staff/stockpile/dashboard/index.js
Labels: corrections

#178 Update:UI/UX / List of Evacuees list
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/helper/staffFamilyService.js
  src/pages/staff/family/index.js
Labels: design

#179 Fix: Staff / Redirect issues
  src/pages/_app.js
Labels: corrections
