Repository Nichi-In-Dev-Dept-1/telenet_hinanjo_web_fe_nextjs, pull requests merged in 2023-09, with the labels that each got.

#1 update UI/UX / components19.0
  .vscode/settings.json
  src/components/dragNdrop/questionnairesView.js
  src/components/index.js
  src/components/input/index.js
  src/components/input/input.js
  src/helper/adminPlaceDetailService.js
  src/pages/admin/components_demo/demo2.js
  src/pages/admin/components_demo/index.js
  src/pages/admin/place/detail/[id].js
  src/pages/index.js
  src/styles/components/_dragDrop.scss
  src/styles/pages/_stockpileMaster.scss
Labels: bug

#5 Evacuation List Screen and Shortage Supplies Screen created with responsive
  public/locales/jp/lang.json
  src/components/modal/detailModal.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/history/place/index.js
  src/pages/admin/shortage-supplies/index.js
  src/styles/components/_dialog.scss
  src/styles/pages/_evacuation.scss
  src/utils/constant.js
Labels: FE_Development Screen

#6 Dashboard screen and History place screen #1991 #1990
  src/components/datatable/normalTable.js
  src/components/modal/deleteModal.js
  src/helper/adminDashboardService.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/history/place/index.js
  src/styles/components/_dialog.scss
  src/styles/components/_table.scss
  src/styles/pages/_dashboard.scss
  src/styles/pages/_historyPlace.scss
  src/styles/pages/pages.scss
  src/utils/constant.js
Labels: FE_Development Screen

#9 Update: UI/UX / Admin sidebar
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/layout/AppMenu.js
  src/pages/admin/external/family/index.js
Labels: design

#10 Fix: UI/UX / Admin ( Login, Forgot, Reset )
  src/pages/admin/forgot-password/index.js
  src/pages/admin/reset-password/index.js
  src/services/authn_authz.services.js
Labels: design, integration

#11 Check: Reset password issues
  src/pages/_app.js
Labels: bug

#12 Check: Reset password issues
  src/pages/_app.js
Labels: bug

#15 Fix: Check reset password changes
  package.json
  src/pages/_app.js
Labels: bug

#16 Fix: Build issuess
  src/pages/admin/evacuation/family-detail/index.js
  src/utils/constant.js
Labels: bug

#18 Fix: Check reset password changes
  src/pages/_app.js
Labels: bug

#19 Likith UI/UX
  src/components/modal/emailSettings.js
  src/pages/_app.js
  src/pages/admin/dashboard/index.js
  src/services/authn_authz.services.js
  src/styles/components/_label.scss
  src/styles/components/components.scss
  src/styles/pages/_historyPlaceMail.scss
Labels: corrections

#20 #2054
  public/locales/en/lang.json
  public/locales/jp/lang.json
  public/themes/lara-light-indigo/theme.css
  src/components/datatable/normalTable.js
  src/components/datatable/rowExpansionTable.js
  src/components/date&time/dateTimeCalendarFloatLabel.js
  src/components/dropdown/selectFloatLabel.js
  src/components/index.js
  src/components/input/inputFloatLabel.js
  src/components/input/textAreaFloatLabel.js
  src/components/label/NormalLabel.js
  src/components/modal/detailModal.js
  src/components/modal/emailSettings.js
  src/helper/adminEvacueeFamilyDetailService.js
  src/helper/adminEvacueesListService.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/forgot-password/index.js
  src/pages/admin/history/place/index.js
  src/pages/admin/login/index.js
  src/pages/admin/reset-password/index.js
  src/pages/admin/shortage-supplies/index.js
  src/styles/components/_label.scss
  src/styles/layout/_footer.scss
  src/styles/layout/_topbar.scss
  src/styles/pages/_common.scss
  src/styles/pages/pages.scss
  src/styles/variables.scss
  src/utils/constant.js
Labels: design
