Repository Nichi-In-Dev-Dept-1/telenet_hinanjo_web_fe_nextjs, pull requests merged in 2023-11, with the labels that each got.

#182 REGISTER CHECK IN
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/staff/register/check-in/index.js
  src/pages/staff/supplies/index.js
  src/services/register_check_in.services.js
Labels: design, integration

#185 Update:UI/UX / Temporary registrants list
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/staff/temporary/family/index.js
Labels: design

#186 Fix:UI/UX /User list table
  src/pages/user/list/index.js
Labels: bug

#187 Fix:UI/UX /#2321
  public/themes/lara-light-indigo/theme.css
  src/pages/admin/shortage-supplies/index.js
  src/pages/user/list/index.js
  src/styles/components/_dialog.scss
  src/styles/pages/_evacuation.scss
Labels: bug

#188 Update:UI/UX / Temporary staff detail screen design
  public/locales/en/lang.json
  src/components/datatable/rowExpansionTable.js
  src/helper/staffFamilyAdmissionService.js
  src/helper/staffFamilyDetailColumnService.js
  src/helper/staffFamilyDetailQuestionsService.js
  src/helper/staffFamilyDetailService.js
  src/pages/admin/stockpile/summary/index.js
  src/pages/staff/temporary/family-detail/index.js
  src/pages/staff/temporary/family/index.js
Labels: design

#189 UI/UX / Staff & Admin ( #2320 )
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/admin/login/index.js
  src/pages/admin/reset-password/index.js
  src/pages/staff/forgot-password/index.js
  src/pages/staff/login/index.js
  src/pages/staff/reset-password/index.js
  src/services/authn_authz.services.js
Labels: design, corrections

#191 Update:UI/UX / List of evacuees details
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/family/index.js
  src/pages/user/dashboard/index.js
Labels: bug, design

#192 updated questionnaire
  src/components/datatable/rowExpansionTable.js
  src/components/modal/stockPileSummaryMailSettingsModal.js
  src/components/modal/stockpileSummaryImageModal.js
  src/pages/admin/questionnaire/individual.js
  src/pages/admin/stockpile/summary/index.js
Labels: bug

#193 Update:UI/UX / Person Count
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/index.js
  src/components/modal/personCountModal.js
  src/components/switch/toggleSwitch.js
  src/pages/staff/family/index.js
  src/styles/pages/_common.scss
Labels: design

#194 Fix:UI/UX List of evacuees
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/index.js
  src/components/modal/qrCodeModal.js
  src/components/qr/barcodeScanner.js
  src/pages/staff/family/index.js
  src/pages/staff/temporary/family/index.js
Labels: bug, design

#195 updated questionnaire and lang file
  public/locales/en/lang.json
  src/components/questionarrie/template/baseTemplate.js
  src/pages/admin/external/family/list/index.js
  src/pages/admin/questionnaire/individual.js
Labels: corrections

#196 Fix: Integration / #2328
  src/pages/user/list/index.js
Labels: bug, integration

#197 Fix: Localization / #2026
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/layout/AppTopbar.js
Labels: design, corrections

#199 Fix: UI/UX / Localization / #2026
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/dropdown/dropdownSelect.js
  src/components/modal/changePasswordModal.js
  src/layout/AppMenu.js
  src/layout/AppTopbar.js
  src/pages/admin/reset-password/index.js
  src/pages/staff/forgot-password/index.js
  src/pages/staff/login/index.js
  src/pages/staff/reset-password/index.js
  src/styles/components/_dropdown.scss
  src/styles/layout/_footer.scss
  src/styles/layout/_menu.scss
  src/styles/layout/_responsive.scss
  src/styles/pages/_common.scss
  src/styles/variables.scss
Labels: design, corrections, integration

#200 supplies issue fixes
  public/locales/en/lang.json
  src/components/incrementDecrement/counter.js
  src/pages/staff/supplies/index.js
  src/styles/pages/_common.scss
  src/styles/variables.scss
Labels: bug

#201 Fix: UI/UX & Integration
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/dropdown/dropdownSelect.js
  src/layout/AppTopbar.js
  src/pages/admin/reset-password/index.js
  src/pages/staff/reset-password/index.js
Labels: bug, design, corrections, integration

#202 Updated Staff screen evacuation Integration
  src/components/modal/stockPileSummaryMailSettingsModal.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/questionnaire/master.js
  src/pages/admin/stockpile/summary/index.js
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/family/index.js
  src/services/staff_evacuation.services.js
Labels: enhancement

#203 Fix: Merge conflicts
  src/pages/staff/family/index.js
Labels: bug

#204 Update: UI/UX / Sidebar
  src/layout/AppMenu.js
Labels: design, corrections

#205 Updated Temporary Registrants Integration
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/family/index.js
  src/pages/staff/temporary/family-detail/index.js
  src/pages/staff/temporary/family/index.js
  src/services/staff_temporary_registrants.services.js
Labels: integration

#206 Fix:UI/UX / Reset Password Jp string change
  public/locales/jp/lang.json
Labels: corrections

#207 Fix: Side bar related issues
  public/themes/lara-light-indigo/theme.css
  src/layout/AppMenu.js
  src/layout/AppMenuitem.js
  src/styles/layout/_menu.scss
  src/styles/layout/layout.scss
  src/styles/layout/tooltip.scss
Labels: design, corrections

#208 Fix:UI/UX / Staff Family List and detail
  public/locales/en/lang.json
  src/components/switch/toggleSwitch.js
  src/helper/index.js
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/temporary/family-detail/index.js
  src/styles/components/_personCount.scss
  src/styles/components/components.scss
Labels: bug

#210 Fix: Merge conflicts
  src/helper/index.js
Labels: corrections

#211 wip check-in check-out Change text center
  src/pages/staff/register/check-in/index.js
  src/pages/user/register/member/index.js
  src/services/check_in_out.services.js
  src/services/index.js
Labels: corrections

#213 Fix:UI/UX / Evacuees String Changes
  public/locales/en/lang.json
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/family/index.js
Labels: corrections

#214 Fix: Merge conflicts
  src/components/modal/staffStockpileEditModal.js
  src/pages/staff/stockpile/dashboard/index.js
Labels: corrections

#215 Fix: UI/UX / Layout issues
  src/components/dropdown/dropdownSelect.js
  src/layout/AppMenuitem.js
  src/layout/AppTopbar.js
  src/styles/layout/_responsive.scss
  src/styles/layout/_topbar.scss
Labels: design, corrections

#216 Fix: UI/UX / Staff External Evacuees List and Details
  public/locales/en/lang.json
  src/pages/staff/external/family-list/index.js
Labels: bug, corrections

#217 updated public evacuees bugs and stock pile fixes
  public/locales/en/lang.json
  src/pages/admin/stockpile/summary/index.js
  src/pages/user/public-evacuees/index.js
  src/services/stockpile_summary.services.js
Labels: bug, corrections

#218 Fix: UI/UX / Header
  src/styles/layout/_topbar.scss
Labels: design, corrections

#220 Fix: UI/UX / Header
  src/components/dropdown/dropdownSelect.js
  src/styles/layout/_topbar.scss
Labels: design, corrections

#221 minor bug on place history
  src/pages/admin/history/place/index.js
Labels: bug

#222 Fix: UI/UX / Dashboard
  src/layout/AppMenuitem.js
Labels: design, corrections

#224 Update: UI/UX / Questionaries Improvement Design
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/datatable/rowExpansionTable.js
  src/components/modal/index.js
  src/components/modal/questionariesCreateEditModal.js
  src/helper/adminQuestionarieService.js
  src/pages/admin/questionnaire/index.js
Labels: design

#226 Fix: Localization
  public/locales/en/lang.json
Labels: corrections

#227 Pagination added for Questionarie dashboard
  src/pages/admin/questionnaire/index.js
Labels: corrections

#228 public evacuees fixes and stockpile
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/staffStockpileCreateModal.js
  src/components/modal/staffStockpileEditModal.js
  src/components/modal/stockpileCreateEditModal.js
  src/helper/index.js
  src/pages/staff/external/family-list/index.js
  src/pages/staff/family/index.js
  src/pages/staff/stockpile/dashboard/index.js
  src/pages/staff/temporary/family/index.js
  src/pages/user/public-evacuees/index.js
  src/services/stockpilestaff.service.js
Labels: corrections

#229 public evacuees bug fix and dropdown api integration
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/staff/stockpile/dashboard/index.js
  src/pages/staff/temporary/family-detail/index.js
  src/pages/user/public-evacuees/index.js
  src/services/stockpilestaff.service.js
Labels: corrections

#230 check in design and integration
  public/locales/en/lang.json
  src/components/datatable/normalTable.js
  src/components/datatable/rowExpansionTable.js
  src/pages/user/register/member/index.js
  src/services/check_in_out.services.js
Labels: design, integration

#231 Fix: Stockpile history
  src/components/dropdown/dropdownSelect.js
  src/layout/AppTopbar.js
  src/layout/context/layoutcontext.js
  src/pages/staff/stockpile/history/index.js
  src/services/common.services.js
Labels: corrections, integration

#232 Fix: UI/UX /Staff stockpile edit inventory and expiry date displaying
  src/components/modal/staffStockpileEditModal.js
  src/pages/staff/stockpile/dashboard/index.js
Labels: bug

#234 Resolved public evacuees minor logic fixes
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/pages/admin/external/family/index.js
  src/pages/user/public-evacuees/index.js
Labels: bug, corrections

#235 Fix:Local Json and Special care modal fix
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/datatable/normalTable.js
  src/components/modal/SpecialCareEditModal.js
  src/components/modal/questionariesCreateEditModal.js
  src/helper/adminQuestionarieService.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/questionnaire/index.js
  src/pages/user/external/index.js
  src/styles/variables.scss
Labels: bug, corrections

#236 Update: Data hiding & Font
  package.json
  public/themes/lara-light-indigo/theme.css
  src/pages/_document.js
  src/pages/staff/login/index.js
  src/pages/user/dashboard/index.js
  src/pages/user/external/index.js
  src/styles/layout/_main.scss
Labels: design, corrections

#237 Table changes
  src/components/modal/adminManagementDeleteModal.js
  src/components/modal/staffManagementDetailModal.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/external/family/detail/index.js
  src/pages/admin/external/family/list/index.js
  src/pages/admin/history/place/index.js
  src/pages/admin/material/index.js
  src/pages/admin/place/index.js
  src/pages/admin/questionnaire/index.js
  src/pages/admin/shortage-supplies/index.js
  src/pages/admin/special/care/index.js
  src/pages/admin/staff-management/index.js
  src/pages/admin/stockpile/master/index.js
  src/pages/admin/stockpile/summary/index.js
  src/pages/staff/external/family-list/index.js
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/family/index.js
  src/pages/staff/register/check-in/index.js
  src/pages/staff/stockpile/dashboard/index.js
  src/pages/staff/stockpile/history/index.js
  src/pages/staff/supplies/index.js
  src/pages/user/dashboard/index.js
  src/pages/user/list/index.js
  src/styles/components/_btn.scss
  src/styles/variables.scss
Labels: bug, corrections

#238 Fix: UI/UX & Integration / Stockpile history
  src/helper/index.js
  src/pages/staff/stockpile/history/index.js
Labels: design, corrections, integration

#240 Fix:UI/UX /Header alignment
  src/layout/AppTopbar.js
Labels: bug

#242 Fix:UI/UX / Questionanarie Dashboard
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/questionariesCreateEditModal.js
  src/pages/admin/questionnaire/index.js
Labels: corrections

#243 Likith UI/ux
  public/locales/en/lang.json
  src/layout/AppTopbar.js
  src/styles/layout/_topbar.scss
Labels: design, corrections

#244 Fix:UI/UX / Questionanarie Dashboard1.0
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/questionariesCreateEditModal.js
Labels: corrections

#245 Updated Staff stock pile edit integration and temp screen design fixes
  src/components/dropdown/selectFloatLabel.js
  src/components/modal/staffStockpileCreateModal.js
  src/components/modal/staffStockpileEditModal.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/stockpile/dashboard/index.js
  src/pages/staff/temporary/family/index.js
Labels: bug, corrections

#246 Fix:UI/UX / Staff management design changes
  public/locales/en/lang.json
  public/locales/jp/lang.json
  public/themes/lara-light-indigo/theme.css
  src/components/datatable/normalTable.js
  src/components/input/index.js
  src/components/input/passwordFloatLabel.js
  src/components/modal/StaffManagementEditModal.js
  src/pages/admin/admin-management/index.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/material/index.js
  src/pages/admin/place/index.js
  src/pages/admin/questionnaire/index.js
  src/pages/admin/staff-management/index.js
  src/pages/admin/stockpile/master/index.js
  src/pages/admin/stockpile/summary/index.js
  src/pages/staff/external/family-list/evacueeDetailModal.js
  src/pages/staff/family/family-detail/index.js
  src/pages/user/list/index.js
  src/styles/components/_dialog.scss
  src/styles/components/_input.scss
Labels: design, corrections

#247 Likith UI/ux
  src/layout/AppTopbar.js
  src/layout/context/layoutcontext.js
  src/pages/admin/forgot-password/index.js
  src/pages/admin/login/index.js
  src/pages/admin/place/detail/index.js
  src/pages/admin/reset-password/index.js
  src/pages/admin/setting/index.js
  src/pages/staff/forgot-password/index.js
  src/pages/staff/login/index.js
  src/pages/staff/reset-password/index.js
  src/pages/user/dashboard/index.js
  src/pages/user/list/index.js
  src/services/authn_authz.services.js
  src/services/common.services.js
Labels: design, corrections, integration

#248 Update/Fix: Sidebar & Build issues
  src/components/modal/StaffManagementEditModal.js
  src/layout/AppMenu.js
Labels: design, corrections

#250 Questionarie dashboard string changes
  src/pages/admin/questionnaire/index.js
  src/styles/components/_dialog.scss
Labels: corrections

#252 updated stock pile import fixes
  src/components/modal/adminManagementImportModal.js
  src/components/modal/stockpileCreateEditModal.js
  src/pages/staff/stockpile/dashboard/index.js
Labels: bug, corrections

#253 Fix: UI/UX Stockpile Summary Table Alignment
  src/pages/admin/external/family/list/index.js
  src/pages/admin/stockpile/summary/index.js
Labels: corrections

#254 updated column header issues in shortage supplies
  src/pages/admin/shortage-supplies/index.js
Labels: corrections

#255 Issues fixed
  public/locales/en/lang.json
  src/pages/admin/external/family/list/index.js
  src/pages/admin/place/index.js
  src/pages/admin/stockpile/master/index.js
  src/pages/staff/temporary/family/index.js
  src/styles/components/_table.scss
Labels: bug, corrections

#257 Likith UI/UX
  public/layout/images/Telenet Logo/Logo_Blue_No padding.png
  public/layout/images/Telenet Logo/Logo_Blue_with padding.png
  public/layout/images/Telenet Logo/Logo_Whie_with padding.png
  public/layout/images/Telenet Logo/Logo_White_No padding.png
  src/pages/admin/admin-management/index.js
  src/pages/admin/place/detail/index.js
  src/pages/admin/staff-management/index.js
  src/pages/user/dashboard/index.js
  src/services/qr_code_create.services.js
  src/services/staffmanagement.service.js
Labels: design, corrections, integration

#258 Username display issue fixed
  src/layout/AppTopbar.js
  src/styles/layout/_topbar.scss
Labels: corrections

#259 Fix: Place list redirection
  src/pages/user/dashboard/index.js
  src/services/index.js
  src/services/user_dashboard.services.js
Labels: corrections, update

#260 Rnd related UI changes
  src/components/modal/staffStockpileCreateModal.js
Labels: corrections

#261 Updated StockPile validation issues
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/modal/staffStockpileCreateModal.js
  src/components/modal/staffStockpileEditModal.js
  src/pages/staff/stockpile/dashboard/index.js
  src/styles/pages/_stockpileMaster.scss
Labels: bug, corrections

#262 Fix:UI/UX / Import modal and External Evacuee Screen Scrolling issue
  src/components/modal/adminManagementImportModal.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/external/family/list/evacueeDetailModal.js
  src/styles/components/_table.scss
Labels: bug, corrections

#263 Fix: UI/UX /Admin History place calendar issue fix
  src/components/date&time/dateTimeCalendarFloatLabel.js
  src/components/modal/staffManagementDetailModal.js
  src/helper/index.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/evacuation/index.js
  src/pages/admin/stockpile/summary/index.js
  src/pages/staff/family/index.js
  src/pages/staff/stockpile/history/index.js
  src/pages/staff/temporary/family/index.js
Labels: corrections

#267 Fix: Build issues
  src/pages/admin/questionnaire/index.js
Labels: corrections

#268 Fix: Build issues
  src/components/modal/staffManagementDetailModal.js
Labels: corrections

#269 Fix: UI/UX /Confirmer search blank screen loading
  src/pages/staff/stockpile/history/index.js
Labels: bug

#273 Fix: UI/UX /Import loading and Table alignment
  src/components/modal/adminManagementImportModal.js
  src/components/modal/staffManagementDetailModal.js
  src/helper/index.js
  src/pages/admin/dashboard/index.js
  src/pages/admin/evacuation/family-detail/index.js
  src/pages/admin/external/family/list/evacueeDetailModal.js
  src/pages/admin/history/place/index.js
  src/pages/staff/register/check-in/index.js
  src/pages/staff/stockpile/history/index.js
  src/pages/staff/supplies/index.js
Labels: bug, corrections

#274 Updated questionnaire integration fixes
  src/components/modal/staffStockpileCreateModal.js
  src/components/questionarrie/template/baseTemplate.js
  src/pages/admin/questionnaire/individual.js
  src/pages/admin/questionnaire/master.js
Labels: bug, corrections

#276 Likith UI/UX
  package.json
  src/pages/admin/headquarters/index.js
Labels: corrections, update

#277 Fix: UI/UX / Table alignment in Staff supplies screen
  src/pages/staff/supplies/index.js
Labels: corrections

#280 Updated questionnaire initial update fixes
  src/components/questionarrie/template/baseTemplate.js
  src/pages/admin/questionnaire/individual.js
  src/pages/admin/questionnaire/master.js
Labels: bug

#281 Fix:UI/UX /Header date and other date display issue fix
  src/layout/AppTopbar.js
  src/pages/admin/history/place/index.js
  src/pages/staff/family/family-detail/index.js
  src/pages/staff/temporary/family-detail/index.js
Labels: corrections

#282 Fix:UI/UX /Import issue fixed in special care and material admin screen
  src/pages/admin/material/index.js
  src/pages/admin/special/care/index.js
  src/services/material.service.js
  src/services/special_care.service.js
Labels: corrections

#283 Minor fix in the modal popup in stockpile edit
  src/components/modal/staffStockpileEditModal.js
Labels: corrections

#284 Fix: UI/UX /After import , datas are not getting reflected immediately
  src/pages/admin/place/index.js
  src/pages/admin/stockpile/master/index.js
  src/services/place.service.js
  src/services/stockpilemaster.service.js
  src/services/stockpilestaff.service.js
Labels: corrections

#285 Map screen design and integration
  public/locales/en/lang.json
  public/locales/jp/lang.json
  src/components/index.js
  src/components/map/GoogleMapComponent.js
  src/components/map/GoogleMapMultiMarker.js
  src/components/map/index.js
  src/pages/user/map/index.js
  src/services/index.js
  src/services/map.services.js
  src/styles/pages/_common.scss
Labels: design, integration
